In [1]:
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
#import ipynb.fs
#from .full.app import app
#from .full.layouts import layout1, layout2, layout3
from jupyter_dash import JupyterDash
import dash_auth
import pandas as pd
import numpy as np
import sys, re
import plotly
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from jitcache import Cache
import dash_table as dt
import dash_bootstrap_components as dbc
import plotly.graph_objs as go
from dash.exceptions import PreventUpdate
from pandas.tseries.offsets import *
import flask

In [2]:
survey_data = pd.read_csv(r'G:\Shared drives\MediSprout\data\survey_data_nov2020')

def parent_desktop(row):
    platform = row['platform']
    
    if row['is_mobile'] == 0:
        if bool(re.search('Mac', str(platform))) == True:
            return 'Mac OS'
        elif bool(re.search('Linux', str(platform))) == True:
            return 'Linux'
        elif bool(re.search('Windows', str(platform))) == True:
            return 'Windows'
        else:
            return 'NaN'
        
def mobile_devices(row):
    platform = row['platform']
    
    if row['is_mobile'] == 1:
        if bool(re.search('iPhone', str(platform))) == True:
            return 'iPhone'
        elif bool(re.search('iPad', str(platform))) == True:
            return 'iPad'
        elif bool(re.search('samsung', str(platform))) == True:
            return 'samsung'
        elif bool(re.search('vivo', str(platform))) == True:
            return 'vivo'
        elif bool(re.search('lenovo', str(platform))) == True:
            return 'lenovo'
        elif bool(re.search('LG', str(platform))) == True:
            return 'LG'
        elif bool(re.search('motorola', str(platform))) == True:
            return 'motorola'
        elif bool(re.search('Pixel', str(platform))) == True:
            return 'Google Pixel'
        elif bool(re.search('OnePlus', str(platform))) == True:
            return 'OnePlus'
        elif bool(re.search('Yulong', str(platform))) == True:
            return 'Yulong'
        elif bool(re.search('LGE', str(platform))) == True:
            return 'LGE'
        elif bool(re.search('TCL', str(platform))) == True:
            return 'TCL'
        elif bool(re.search('ZTE', str(platform))) == True:
            return 'ZTE'
        elif bool(re.search('Xiaomi', str(platform))) == True:
            return 'Xiaomi'
        elif bool(re.search('AlcatelOneTouch', str(platform))) == True:
            return 'AlcatelOneTouch'
        elif bool(re.search('HUAWEI', str(platform))) == True:
            return 'HUAWEI'
        elif bool(re.search('Amazon', str(platform))) == True:
            return 'Amazon'
        elif bool(re.search('ALCATEL', str(platform))) == True:
            return 'ALCATEL'
        elif bool(re.search('TINNO', str(platform))) == True:
            return 'TINNO'
        elif bool(re.search('BLU', str(platform))) == True:
            return 'BLU'
        elif bool(re.search('Alco', str(platform))) == True:
            return 'Alco'
        elif bool(re.search('Innovations', str(platform))) == True:
            return 'Innovations'
        elif bool(re.search('HMD', str(platform))) == True:
            return 'HMD/Nokia'
        elif bool(re.search('Sony', str(platform))) == True:
            return 'Sony'
        elif bool(re.search('HTC', str(platform))) == True:
            return 'HTC'
        elif bool(re.search('LENOVO', str(platform))) == True:
            return 'LENOVO'
        elif bool(re.search('asus', str(platform))) == True:
            return 'asus'
        elif bool(re.search('Alco', str(platform))) == True:
            return 'Alco'
        elif bool(re.search('LENOVO', str(platform))) == True:
            return 'LENOVO'
        else:
            return 'Other'

def classify_mobile_type(row):
    platform = row['platform']
    
    if row['is_mobile'] == 1:
        if bool(re.match('Apple iP\w*', str(platform))) == True:
            return 'iOS'
        else:
            return 'Android'
    else:
        return 'NA'
    
    return row

def parent_desktop(row):
    platform = row['platform']
    
    if row['is_mobile'] == 0:
        if bool(re.search('Mac', str(platform))) == True:
            return 'Mac OS'
        elif bool(re.search('Linux', str(platform))) == True:
            return 'Linux'
        elif bool(re.search('Windows', str(platform))) == True:
            return 'Windows'
        else:
            return 'NaN'

        
survey_data['mobile_type'] = survey_data.apply(lambda row: classify_mobile_type(row), axis=1)
survey_data['mobile_devices'] = survey_data.apply(lambda row: mobile_devices(row), axis=1)
survey_data['parent_desktop'] = survey_data.apply(lambda row: parent_desktop(row), axis=1)
survey_data['created_on'] = pd.to_datetime(survey_data['created_on'], format='%Y-%m-%d %H:%M:%S.%f')
survey_data['created_on_date'] = survey_data['created_on'].dt.date
survey_data['months'] = pd.to_datetime(survey_data['created_on'], format='%Y-%m-%d %H:%M:%S.%f').dt.strftime('%Y-%m')


desktop_df = survey_data.groupby(['months', 'parent_desktop', 'source', 'is_satisfied'])['visit_id'].count().to_frame().reset_index()
mobile_df = survey_data.groupby(['months', 'mobile_devices', 'source', 'is_satisfied'])['visit_id'].count().to_frame().reset_index()
mom_df = survey_data.groupby(['months', 'is_satisfied', 'source', 'rating'])['visit_id'].count().to_frame().reset_index()

app = JupyterDash(__name__)
df1 = mom_df
df1['rating'] = df1['rating'].astype(int)
df2 = mobile_df
df3 = desktop_df
survey_data

c:\users\vishaal bhardwaj\plotly practice\env\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (0,2,3,4) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,id,source,visit_id,is_satisfied,rating,feedback,member_healthcare_org_rel_id,patient_id,created_on,updated_on,...,client_version,screen_size,connection_type,build_version,n_minute_duration,mobile_type,mobile_devices,parent_desktop,created_on_date,months
0,1,Clinician,17486,1,NaN,NaN,676.0,647.0,2019-03-19 17:56:05,2019-03-19 17:56:05,...,NaN,NaN,NaN,NaN,1.6667,NA,None,NaN,2019-03-19,2019-03
1,2,Clinician,17488,1,NaN,NaN,322.0,389.0,2019-03-20 17:35:56,2019-03-20 17:35:56,...,NaN,NaN,NaN,NaN,22.7667,NA,None,NaN,2019-03-20,2019-03
2,3,Patient,17488,1,NaN,NaN,322.0,389.0,2019-03-20 17:35:57,2019-03-20 17:35:57,...,NaN,NaN,NaN,NaN,22.7667,NA,None,NaN,2019-03-20,2019-03
3,4,Patient,17490,0,NaN,NaN,237.0,87.0,2019-03-20 18:21:10,2019-03-20 18:21:10,...,NaN,NaN,NaN,NaN,52.0500,NA,None,NaN,2019-03-20,2019-03
4,5,Clinician,17490,0,NaN,shut down mid session,237.0,87.0,2019-03-20 18:21:38,2019-03-20 18:21:38,...,NaN,NaN,NaN,NaN,52.0500,NA,None,NaN,2019-03-20,2019-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184451,184455,Patient,316003,0,4,NaN,66404.0,215848.0,2020-11-16 22:59:35,2020-11-16 22:59:35,...,86.0.4240.193,1440 x 900,NaN,NaN,0.0167,NA,None,Mac OS,2020-11-16,2020-11
184452,184456,Patient,316111,1,5,NaN,4045.0,305919.0,2020-11-16 22:59:56,2020-11-16 22:59:56,...,NaN,NaN,NaN,NaN,21.0000,Android,Other,None,2020-11-16,2020-11
184453,184457,Patient,316100,1,4,NaN,65240.0,139736.0,2020-11-16 23:00:02,2020-11-16 23:00:02,...,NaN,NaN,NaN,NaN,36.3167,Android,Other,None,2020-11-16,2020-11
184454,184458,Clinician,316113,1,4,NaN,4097.0,305937.0,2020-11-16 23:01:21,2020-11-16 23:01:21,...,NaN,NaN,NaN,NaN,22.9167,Android,Other,None,2020-11-16,2020-11
184455,184459,Patient,316119,1,3,NaN,4143.0,304135.0,2020-11-16 23:02:02,2020-11-16 23:02:02,...,NaN,NaN,NaN,NaN,10.9667,Android,Other,None,2020-11-16,2020-11

In [3]:
#just data table
app = JupyterDash(__name__,
external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = html.Div(
    [dbc.Button("start", color="success",
               className="mr-1")]
)

dropdown = html.Div([
    html.Label('mobile devices'),
    dcc.Dropdown(id='dropdown_d1', options=[{'label':x, 'value':x} for x in df2.sort_values('mobile_devices')['mobile_devices'].unique()], 
                 value=None, multi=False),
    html.Label('source'),
    dcc.Dropdown(id='dropdown_d2', options=[], value=None)
])

final_table = html.Div(id="final_table")

app.layout = html.Div([dropdown, final_table])

@app.callback(Output('dropdown_d2', 'options'),
          [
            Input('dropdown_d1', 'value'),
          ])
def update_dropdown_2(d1):
    print(d1)
    if(d1 != None):
        df_filtered = df2[(df2["mobile_devices"]==d1)]
        return [{'label': i, 'value': i} for i in df_filtered["source"].unique()]
    else:
        return []


@app.callback(Output('final_table', 'children'),
          [
            Input('dropdown_d1', 'value'),
            Input('dropdown_d2', 'value'),
          ])
def update_table(d1, d2):

    if(d1 != None and d2 != None):
        df_filtered = df2[(df2["mobile_devices"]==d1) & (df2["source"]==d2)]

        return [dt.DataTable(
            id='table',
            columns=[{"name": i, "id": i} for i in df_filtered.columns],
            data=df_filtered.to_dict('records'),
        )]
    else:
        print("none")
        return []


if __name__ == "__main__":
    app.run_server(debug=True, port=8054)

Dash app running on http://127.0.0.1:8054/

In [4]:
df2

      months mobile_devices     source is_satisfied  visit_id
0    2019-04          Other    Patient            1        10
1    2019-05          Other    Patient            1        21
2    2019-06          Other  Clinician            1         1
3    2019-06          Other    Patient            0         1
4    2019-06          Other    Patient            1        16
..       ...            ...        ...          ...       ...
370  2020-10         iPhone  Clinician            1         1
371  2020-11          Other  Clinician            1       577
372  2020-11          Other    Patient            1      6395
373  2020-11           iPad  Clinician            0         6
374  2020-11         iPhone  Clinician            0         1

[375 rows x 5 columns]

In [5]:
#data table with bar and pie chart
app = JupyterDash(__name__)

colors = {
    'background': '#111111',
    'text': '#7FDBFF'
}

dff = df2
app.layout = html.Div([
    html.Div([
        dt.DataTable(
            id='datatable_id',
            data=dff.to_dict('records'),
            columns=[
                {"name": i, "id": i, "deletable": False, "selectable": False} for i in dff.columns
            ],
            style_header={'backgroundColor': 'rgb(30, 30, 30)'},
            style_cell={
                'backgroundColor': 'rgb(50, 50, 50)',
                'color': 'white'
            },
            editable=False,
            filter_action="native",
            sort_action="native",
            sort_mode="multi",
            row_selectable="multi",
            row_deletable=False,
            selected_rows=[],
            #page_action="native",
            #page_current= 0,
            #page_size= 6,
            page_action='none',
            fixed_rows={ 'headers': True, 'data': 0 },
            virtualization=False,
            style_cell_conditional=[
                {'if': {'column_id': 'mobile_devices'},
                 'width': '40%', 'textAlign': 'left'},
                {'if': {'column_id': 'visit_d'},
                 'width': '30%', 'textAlign': 'left'},
                {'if': {'column_id': 'is_satisfied'},
                 'width': '30%', 'textAlign': 'left'}
            ],
        ),
    ],className='row'),
    
    html.Div([
        html.Div([
            dcc.Dropdown(id='linedropdown',
                options=[
                    {'label': 'visit_id', 'value': 'visit_id'},
                    {'label': 'is_satisfied', 'value': 'is_satisfied'}
                ],
                value='mobile_devices',
                multi=False,
                clearable=False
            ),
        ],className='six columns'),

        html.Div([
        dcc.Dropdown(id='piedropdown',
            options=[
                {'label': 'visit_id', 'value': 'visit_id'},
                {'label': 'is_satisfied', 'value': 'is_satisfied'}
            ],
            value='is_satisfied',
            multi=False,
            clearable=False
        ),
        ],className='six columns'),

    ],className='row'),
    
     html.Div([
        html.Div([
            dcc.Graph(id='linechart1'),
        ],className='six columns'),

        html.Div([
            dcc.Graph(id='piechart1'),
        ],className='six columns'),

    ],className='row'),


])

@app.callback(
    [Output('piechart1', 'figure'),
     Output('linechart1', 'figure')],
    [Input('datatable_id', 'selected_rows'),
     Input('piedropdown', 'value'),
     Input('linedropdown', 'value')]
)

def update_data(chosen_rows,piedropval,linedropval):
    if len(chosen_rows)==0:
        df_filterd = dff[dff['mobile_devices'].isin(['iPhone', 'iPad'])]
    else:
        print(chosen_rows)
        df_filterd = dff[dff.index.isin(chosen_rows)]

    pie_chart=px.pie(
            data_frame=df_filterd,
            names='mobile_devices',
            values=piedropval,
            hole=.3,
            labels={'mobile_devices':'Mobile Devices'}
            )
    
    #extract list of chosen countries
    list_chosen_devices=df_filterd['mobile_devices'].tolist()
    #filter original df according to chosen countries
    #because original df has all the complete dates
    df_line = dff[dff['mobile_devices'].isin(list_chosen_devices)]
    
    line_chart = px.line(
            data_frame=df_line,
            x='months',
            y=linedropval,
            color='mobile_devices',
            labels={'mobile_devices':'Mobile Devices', 'months':'Months'},
            )
    line_chart.update_layout(uirevision='foo')

    return (pie_chart,line_chart)

#------------------------------------------------------------------

if __name__ == '__main__':
    app.run_server(debug=True, port=8043)

Dash app running on http://127.0.0.1:8043/

SINGLE PAGE TEMPLATE

In [6]:

app = JupyterDash(__name__, external_stylesheets=[
        'https://codepen.io/chriddyp/pen/bWLwgP.css'])

app.layout = html.Div([
    html.Div([
        html.Label('mobile devices'),
        dcc.Dropdown(id='dropdown_d1', options=[{'label':x, 'value':x} for x in df2.sort_values('mobile_devices')['mobile_devices'].unique()], 
                     value=None, multi=True),
        html.Label('source'),
        dcc.Dropdown(id='dropdown_d2', options=[{'label': i, 'value': i} for i in df2.sort_values('mobile_devices')["source"].unique()],
                     value=None, multi=True)
    ]),
    html.Div(id="final_table", className="six columns"),
    html.Div([
        html.Div([
            dcc.Graph(id='line_chart'),
        ],className="six columns"),
        html.Div([
            dcc.RangeSlider(
                id="rangeslider",
                pushable=2,
                marks = {i: {'label': i} for i in df2['months']}
            )
        ], className="six columns")
    ])
])

#app.layout = html.Div([dropdown, final_table, line_chart], className="row")

@app.callback([
    Output('final_table','children'),
    Output('line_chart', 'figure')],
    [Input('dropdown_d1', 'value'),
     Input('dropdown_d2', 'value')])

def update_table(d1, d2):
    
    if(d1 != None and d2 != None):
        df_filtered = df2[df2["mobile_devices"].isin(d1) & df2["source"].isin(d2)]
        
    elif d1 != None:
        df_filtered = df2[df2["mobile_devices"].isin(d1)]
        
    elif d2 != None:
        df_filtered = df2[df2["source"].isin(d2)]
        
    else:
        df_filtered = df2
        
    dataTable = [dt.DataTable(
            id='table', 
            columns = [{"name": i, "id": i} for i in df_filtered.columns],
            data=df_filtered.to_dict('records'),
            page_action='none',
            style_table={'height': '500px', 'overflowY': 'auto'}
        )]
        
    #list_chosen_devices=df_filtered['mobile_devices'].unique().tolist()
    #df_line = df2[df2['mobile_devices'].isin(list_chosen_devices)]
    df_line = df_filtered.groupby(['months', 'mobile_devices'])['visit_id'].sum().to_frame().reset_index()
    
    fig = px.line(df_line, 
                      x="months", 
                      y='visit_id', 
                      color='mobile_devices', 
                      height=600)
    fig.update_layout(yaxis={'title':'visits'},
                      title={'text':'visits MoM',
                      'font':{'size':28},'x':0.5,'xanchor':'center'},
                     autosize=False, height=500,
                      xaxis=dict(
        rangeselector=dict(
            buttons=list([
                dict(count=1,
                     label="1m",
                     step="month",
                     stepmode="backward"),
                dict(count=3,
                    label="3m",
                    step="month",
                    stepmode="backward"),
                dict(count=6,
                     label="6m",
                     step="month",
                     stepmode="backward"),
                dict(count=1,
                     label="YTD",
                     step="year",
                     stepmode="todate"),
                dict(count=1,
                     label="1y",
                     step="year",
                     stepmode="backward"),
                dict(step="all")
            ])
        ),
        rangeslider=dict(
            visible=True
        ),
        type="date"
    )
                     )
    
    return dataTable, fig

if __name__ == '__main__':
    app.run_server(debug=True, port=8051)

Dash app running on http://127.0.0.1:8051/

#flask login
from flask_login import LoginManager, UserMixin
app = Flask(__name__)

login = LoginManager(app)

class User(UserMixin, db.Model):

In [7]:
from flask import Flask 
from flask_sqlalchemy import SQLAlchemy 
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user

app = Flask(__name__)

app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite'
app.config['SECRET_KEY'] = 'secret'

db = SQLAlchemy(app)
login_manager = LoginManager()
login_manager.init_app(app)

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(30), unique=True)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

@app.route('/')
def index():
    user = User.query.filter_by(username='Anthony').first()
    login_user(user)
    return 'You are now logged in!'

@app.route('/logout')
@login_required
def logout():
    logout_user()
    return 'You are now logged out!'

@app.route('/home')
@login_required
def home():
    return 'The current user is ' + current_user.username 

if __name__ == '__main__':
    app.run(debug=True)

c:\users\vishaal bhardwaj\plotly practice\env\lib\site-packages\flask_sqlalchemy\__init__.py:833: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  warnings.warn(FSADeprecationWarning(

SystemExit: 1

c:\users\vishaal bhardwaj\plotly practice\env\lib\site-packages\IPython\core\interactiveshell.py:3426: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

In [ ]:
df_filtered = df2[df2["mobile_devices"].isin(['iPhone', 'iPad']) & df2["source"].isin(['Patient', 'Clinician'])]
list_chosen_devices=df_filtered['mobile_devices'].unique().tolist()
df_line = df2[df2['mobile_devices'].isin(list_chosen_devices)]
df_line = df_line.groupby(['months', 'mobile_devices'])['visit_id'].sum().to_frame().reset_index()
fig = px.line(df_line, 
                      x="months", 
                      y='visit_id', 
                      color='mobile_devices', 
                      height=600)
fig

{i: {'label': i} for i in df2['months']}#range slider v1
xaxis=dict(
        rangeselector=dict(
            buttons=list([
                dict(count=1,
                     label="1m",
                     step="month",
                     stepmode="backward"),
                dict(count=6,
                     label="6m",
                     step="month",
                     stepmode="backward"),
                dict(count=1,
                     label="YTD",
                     step="year",
                     stepmode="todate"),
                dict(count=1,
                     label="1y",
                     step="year",
                     stepmode="backward"),
                dict(step="all")
            ])
        ),
        rangeslider=dict(
            visible=True
        ),
        type="date"
    )

In [ ]:
{i: {'label': i} for i in df2['months']}

In [ ]:
df_line.groupby(['months'])['visit_id'].sum().to_frame()

In [ ]:
df_line.query("months == '2020-03'")

In [ ]:
'''    
    elif not d1:
        df_filtered = df2[(df2["mobile_devices"].isin([d1]))]

    elif not d2:
        df_filtered = df2[(df2["source"].isin([d2]))]
    '''

In [ ]:
def update_table(d1):
    if(len(d1) != 0):
        df_filtered = df2[(df2["mobile_devices"].isin([d1]))]
        
        return [dt.DataTable(
            id='table', 
            columns = [{"name": i, "id": i} for i in df_filtered.columns],
            data=df_filtered.to_dict('records'), )]

In [ ]:
update_table([])

In [ ]:
df_filtered = df2[(df2["mobile_devices"].isin(['Amazon']))]
df_filtered

In [ ]:
[{'label': i, 'value': i} for i in df_filtered["source"].unique()]

In [ ]:
def update_table(d1, d2):
    
    if(d1 != None and d2 != None):
        df_filtered = df2[df2['mobile_devices'].isin(d1) & df2['source'].isin(d2)]
        
        return df_filtered
    
    #[dt.DataTable(
            #id='table', 
            #columns = [{"name": i, "id": i} for i in df_filtered.columns],
            #data=df_filtered.to_dict('records'), 
        #)]

In [ ]:
update_table(['iPhone', 'iPad'], ['Patient', 'Clinician'])

In [ ]:
#fixed multi output
app = JupyterDash(__name__)

app.layout = html.Div(
    [dbc.Button("start", color="success",
               className="mr-1")]
)

app.layout = html.Div([
    html.Label('mobile devices'),
    dcc.Dropdown(id='dropdown_d1', options=[{'label':x, 'value':x} for x in df2.sort_values('mobile_devices')['mobile_devices'].unique()], 
                 value=None, multi=False),
    #html.Label('source'),
    #dcc.Dropdown(id='dropdown_d2', options=[{'label': i, 'value': i} for i in df2.sort_values('mobile_devices')["source"].unique()]
                 #, value=None, multi=True),
    html.Div([
        html.Div([
            dcc.Graph(id='graph'),
            dt.DataTable(
            id='data-table', 
            columns = [{"name": i, "id": i} for i in df2.columns],
            )
        ])
    ])
])

@app.callback([
    Output('graph', 'figure'),
    Output('data-table', 'data'),
    Output('data-table', 'columns')],
    [Input('dropdown_d1', 'value'),
    ])

def multi_output(value):
    if value is None:
        raise PreventUpdate
    
    selected = df2[df2['mobile_devices']==value]
    columns = [{'name': k, 'id': k} for k in selected.columns]
    figure = px.line(selected, 
                      x="months", 
                      y='visit_id', 
                      color='mobile_devices', 
                      height=600)
    
    return figure, selected, columns
    
app.run_server(debug=True, port=8046)

In [ ]:
sample_data = {
    'series': {
        'data': [
            {'title': 'Game of Thrones', 'score': 9.5},
            {'title': 'Stranger Things', 'score': 8.9},
            {'title': 'Vikings', 'score': 8.6}
        ],
        'style': {
            'backgroundColor': '#ff998a'
        }
    },
    'movies': {
        'data': [
            {'title': 'Rambo', 'score': 7.7},
            {'title': 'The Terminator', 'score': 8.0},
            {'title': 'Alien', 'score': 8.5}
        ],
        'style': {
            'backgroundColor': '#fff289'
        }
    }
}

app = JupyterDash(__name__)

app.layout = html.Div([
    html.H1('Multi output example'),
    dcc.Dropdown(id='data-dropdown', options=[
        {'label': 'Movies', 'value': 'movies'},
        {'label': 'Series', 'value': 'series'}
    ], value='movies'),
    html.Div([
        dcc.Graph(id='graph'),
        dt.DataTable(id='data-table', columns=[
            {'name': 'Title', 'id': 'title'},
            {'name': 'Score', 'id': 'score'}
        ])
    ])
], id='container')


@app.callback([
    Output('graph', 'figure'),
    Output('data-table', 'data'),
    Output('data-table', 'columns'),
    Output('container', 'style')
], [Input('data-dropdown', 'value')])
def multi_output(value):
    if value is None:
        raise PreventUpdate

    selected = sample_data[value]
    data = selected['data']
    columns = [
        {'name': k.capitalize(), 'id': k}
        for k in data[0].keys()
    ]
    figure = go.Figure(
        data=[
            go.Bar(x=[x['score']], text=x['title'], name=x['title'])
            for x in data
        ]
    )

    return figure, data, columns, selected['style']

if __name__ == '__main__':
    app.run_server(debug=True, port=8056)

In [ ]:
df2[df2['mobile_devices']=='iPhone']